src/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path("add/", views.add, name="add"),
    path("inc/", views.increase_quantity, name="inc"),
    path("dec/", views.decrease_quantity, name="dec"),
    path("remove/", views.remove, name="remove"),
    path('', views.details, name="details"),
]

src/menuFacil/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from . import views, settings

admin.site.site_title = "Menu Fácil site admin"
admin.site.site_header = "Menu Fácil administration"
admin.site.index_title = "Menu Fácil administration"

urlpatterns = [
    path("", views.index, name="home"),
    path("account/", include("account.urls")),
    path('admin/', admin.site.urls),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("restaurant/", include("restaurant.urls")),
    path("tab/", include("tab.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT})]
    urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT})]

src/restaurant/urls.py
from django.urls import path

from . import views

app_name = 'restaurant'
urlpatterns = [
    path('', views.RestaurantsView.as_view(), name='index'),
    path('<uuid:restaurant_id>/', views.menu, name='detail'),
    path('qrcode/<uuid:tab_id>/', views.get_qrcode, name='qrcode'),
    path('sales/<uuid:restaurant_id>/', views.sales, name='sales'),
    path('search/', views.search, name='search')
]

src/tab/urls.py
from django.urls import path

from . import views

app_name = 'tab'
urlpatterns = [
    path('', views.details, name='details'),
    path('present/', views.present, name='present'),
    path('history/', views.history, name='history'),
    path('paid/', views.paid, name='paid'),
    path('pay/physical/', views.pay_physical, name='physical'),
    path('pay/online/', views.pay_online, name='online'),
    path('pay/confirm/', views.confirm_payment, name='confirm'),
    path('remove/', views.remove_tab, name='remove'),
    path('get_page/', views.get_tab_page, name='get_page')
]

src/restaurant/models.py
from decimal import Decimal
from uuid import uuid4
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Restaurant(models.Model):
    """Model representing a Restaurant."""
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    logo = models.ImageField(upload_to='restaurant/logos', blank=True)
    message = models.TextField(blank=True)

    def __str__(self) -> str:
        return str(self.name)

    def get_most_popular_foods(self):
        foods = Food.objects.filter(menu__restaurant=self)
        popular_foods = foods.order_by('-item__quantity').distinct()[:5]
        return popular_foods

    def get_total_sales(self) -> int:
        foods = Food.objects.filter(menu__restaurant=self)
        return sum(food.get_total_sales() for food in foods)

    def get_total_sales_amount(self) -> Decimal:
        foods = Food.objects.filter(menu__restaurant=self)
        return sum((food.get_total_sales_amount() for food in foods), Decimal(0))

PERCENTAGE_VALIDATOR = [MinValueValidator(0), MaxValueValidator(100)]

class Promotion(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, editable=False)
    menu = models.ManyToManyField('Menu')
    name = models.CharField(max_length=200)
    discount = models.DecimalField(max_digits=3, decimal_places=0, default=Decimal(0),
                                   validators=PERCENTAGE_VALIDATOR)
    active = models.BooleanField(default=False)

    def __str__(self) -> str:
        return str(self.name)

class Menu(models.Model):
    """Model representing a Menu of a Restaurant."""
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, editable=False)
    name = models.CharField(max_length=200)

    def get_best_promotion(self) -> Promotion | None:
        return self.promotion_set.filter(active=True).order_by('-discount').first() # type: ignore

    def __str__(self) -> str:
        return str(self.name)

class Food(models.Model):
    """Model representing a Food item."""
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    menu = models.ForeignKey(Menu, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=5, decimal_places=2,
                default=Decimal("1.99"), # Decimal needs to be a string or it will have imprecision
                validators=[MinValueValidator(Decimal("0.00"))])
    description = models.TextField(blank=True)
    photo = models.ImageField(upload_to='restaurant/food_photos', blank=True)
    hidden = models.BooleanField(default=False)

    class FoodType(models.TextChoices):
        """Enums for the types of Food possible."""
        MAIN = "MN", "Main"
        SIDE = "SD", "Side"
        DRINK = "DK", "Drink"
        DESSERT = "DS", "Dessert"

    food_type = models.CharField(
        max_length=2,
        choices=FoodType.choices,
        default=FoodType.MAIN,
    )

    def get_price(self) -> Decimal:
        best_promotion = self.menu.get_best_promotion()  if self.menu else None
        return self.price if not best_promotion else self.price * (1 - best_promotion.discount / 100)

    def get_total_sales(self) -> int:
        return self.item_set.aggregate(models.Sum('quantity'))['quantity__sum'] or 0 # type: ignore

    def get_total_sales_amount(self) -> Decimal:
        return self.item_set.aggregate(models.Sum('price'))['price__sum'] or Decimal(0) # type: ignore

    def __str__(self) -> str:
        return str(self.name)

src/restaurant/views.py
import io
from typing import Any
from uuid import UUID
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import FileResponse
from django.template.loader import get_template
from django.views.decorators.http import require_POST
from django.contrib.admin.views.decorators import staff_member_required
from xhtml2pdf import pisa

from menuFacil.validation import contains
from .models import Restaurant

# Create your views here.
class RestaurantsView(generic.ListView):
    template_name = 'restaurant/index.html'
    context_object_name = 'restaurant_list'

    def get_queryset(self) -> QuerySet[Any]:
        return Restaurant.objects.order_by('name')

def menu(request: HttpRequest, restaurant_id: UUID) -> HttpResponse:
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)

    return render(request, 'restaurant/detail.html', {'restaurant': restaurant})

def create_pdf(html, name: str) -> FileResponse:
    buffer = io.BytesIO()
    pdf = pisa.pisaDocument(io.BytesIO(html.encode("ISO-8859-1")), buffer)
    buffer.seek(0)
    if not pdf.err: # type: ignore
        return FileResponse(buffer, as_attachment=True, filename= f"{name}.pdf")
    return FileResponse('Error Rendering PDF', status=400)

@staff_member_required
def get_qrcode(request: HttpRequest, tab_id: UUID) -> FileResponse:
    html = get_template('restaurant/qrcode.html').render({'tab_id': str(tab_id)})
    return create_pdf(html, f"{str(tab_id).split('-')[0]}-qrcode")

@staff_member_required
def sales(request: HttpRequest, restaurant_id: UUID):
    restaurant = Restaurant.objects.get(pk=restaurant_id)
    html = get_template('restaurant/sales.html').render({'restaurant': restaurant})
    return create_pdf(html, f"{restaurant.name}-sales")

@require_POST
def search(request: HttpRequest) -> HttpResponse:
    if not contains(request.POST, ['search']):
        return JsonResponse({"success": False}, status=400)
    
    request.session['search'] = request.POST['search']

    return JsonResponse({"success": True}, status=200)

src/restaurant/templates/restaurant/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ restaurant.name }}
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'restaurant/css/detail.css' %}" />
{% endblock %}

{% block content %}
<body class="sub_page">
  

  <div class="menu" style="padding-bottom: 15vh;">
    <div class="heading_container heading_center" style="padding-top: 2vh; padding-bottom: 5vh">
      <h1 class="texto">{{ restaurant.name }}</h1>
      <h2 class="texto">{{ restaurant.message }}</h2>
    </div>
    <div class="menus" style="padding-bottom: 50px;">
      {% csrf_token %}
      <script>
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
        const addURL = "{% url 'cart:add' %}"
      </script>
      {% for menu in restaurant.menu_set.all %}
        <section class="menu-item">
          <h2>{{ menu.name }}</h2>
          {% for food in menu.food_set.all %}
            <div class="container-food" data-food-id="{{ food.id }}" data-restaurant-id="{{ restaurant.id }}">
              {% if not food.hidden %}
                <a>
                  {% if food.photo %}
                    <img src="{{ food.photo.url }}" alt="{{ food.name }}" />
                  {% endif %}
                  <p>{{ food.name }}</p>
                  <p>R$ {{ food.get_price|floatformat:2 }}</p>
                  <p><small>{{ food.description }}</small></p>
                </a>
                <script>
                  window.onload = function() {
                    
                    
                    const foodElements = document.querySelectorAll('.container-food');
                
                    foodElements.forEach(function(foodElement) {
                      foodElement.addEventListener('click', function() {
                        const foodId = this.dataset.foodId;
                        const restaurantId = this.dataset.restaurantId;
                
                        SendPost(
                          csrftoken,
                          addURL,
                          { food: foodId, restaurant: restaurantId },
                          function (data, textStatus, jqXHR) {
                            location.reload();
                          },
                          function (jqXHR, textStatus, errorThrown) {
                            console.log(errorThrown);
                            location.reload();
                          }
                        );
                      });
                    });
                  };
                </script>
              {% endif %}
            </div>
          {% endfor %}
        </section>
      {% endfor %}
    </div>
  </div>
 
</body>
{% endblock %}

src/restaurant/templates/restaurant/index.html
{% extends "base.html" %}
{% load static %}
{% load rest_tags %}

{% block title %}Restaurants{% endblock %}

{% block head %}
{% csrf_token %}
<script>
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
</script>
{% endblock %}

{% block slider%}
     <!-- slider section -->
    <div>
        <section class="slider_section">
            <div class="container ">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                <div class="detail-box">
                    <h1>
                    Discover Restaurants
                    </h1>
                    <p>
                    Savor the Flavor: Where Culinary Dreams and Digital Menus Unite!
                    </p>
                </div>
                <div class="find_container ">
                    <div class="container">
                    <div class="row">
                        <div class="col">
                        <form>
                            <div class="form-row ">
                            <div class="form-group col-lg-5">
                                <input type="text" class="form-control" id="inputName" placeholder="Restaurant Name" value='{{request.session|get_item:"search"}}' autocomplete="off">
                            </div>
                      
                            <div class="form-group col-lg-3">
                                <div class="btn-box">
                                <button type="submit" class="btn " id="search">Search</button>
                                </div>
                            </div>
                            <script>
                              const URL = "{% url 'restaurant:search' %}"

                              document.getElementById('search').onclick = function () {
                                name = document.getElementById('inputName').value
                                SendPost(
                                  csrftoken,
                                  URL,
                                  {
                                    search: name,
                                  },
                                  function (response) {
                                    location.reload()
                                  },
                                  function (error) {
                                    console.log(error)
                                  }
                                )
                              }
                            </script>
                            </div>
                        </form>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
            <div class="slider_container">
              {% with search=request.session|get_item:"search" %}
                {% with rests=restaurant_list|filter_name:search %}
                  {% if rests %}
                  {% for restaurant in rests %}
                  <section class="item">
                      <div class="img-box">
                          <a href="{% url 'restaurant:detail' restaurant.id %}" class="cart">
                              {% if restaurant.logo %}
                                  <img src="{{ restaurant.logo.url }}" alt="{{ restaurant.name }}" href="{% url 'restaurant:detail' restaurant.id %}" >      
                              {% endif %}
                          </a>
                      </div>
                      <div class="detail-box"></div>
                  </section>
                  {% endfor %}
                  {% else %}
                  <div class="container heading_center">
                    <p style="padding: 10vh;">No restaurants<br>are available.</p>
                  </div>
                  {% endif %}
                {% endwith %}
              {% endwith %}
        
            </div>
        </section>
    </div> 
{% endblock %}

     <!-- recipe section -->
{%block content%}
  <section class="recipe_section layout_padding-top">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
            For Every Culinary Preference...
        </h2>
      </div>
      <div class="row">
        <div class="col-sm-6 col-md-4 mx-auto">
          <div class="box">
            <div class="img-box">
              <img src="{% static 'MenuFacil/images/r1.jpg' %}" class="box-img" alt="">
            </div>
            <div class="detail-box">
              <h4>
                Fast-Food
              </h4>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-4 mx-auto">
          <div class="box">
            <div class="img-box">
              <img src="{% static 'MenuFacil/images/r2.jpg' %}" class="box-img" alt="">
            </div>
            <div class="detail-box">
              <h4>
                Italian 
              </h4>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-4 mx-auto">
          <div class="box">
            <div class="img-box">
              <img src="{% static 'MenuFacil/images/r3.jpg' %}" class="box-img" alt="">
            </div>
            <div class="detail-box">
              <h4>
                Japanese
              </h4>
            </div>
          </div>
        </div>
      </div>
      <div class="btn-box">
        <a href="">
          Order Now
        </a>
      </div>
    </div>
  </section>
  <!-- end recipe section -->

  <!-- app section -->
  <section class="app_section">
    <div class="container">
      <div class="col-md-9 mx-auto">
        <div class="row">
          <div class="col-md-7 col-lg-8">
            <div class="detail-box">
              <h2>
                <span> Get the</span> <br>
                MenuFácil App
              </h2>
              <p>
                Navigate a world of culinary delights at your fingertips with the MenuFácil mobile app. 
              </p>
              <div class="app_btn_box">
                <a href="" class="mr-1">
                  <img src="{% static 'MenuFacil/images/google_play.png' %}" class="box-img" alt="">
                </a>
                <a href="">
                  <img src="{% static 'MenuFacil/images/app_store.png' %}" class="box-img" alt="">
                </a>
              </div>
              <a href="" class="download_btn">
                Download Now
              </a>
            </div>
          </div>
          <div class="col-md-5 col-lg-4">
            <div class="img-box">
              <img src="{% static 'MenuFacil/images/mobile.png' %}" class="box-img" alt="">
            </div>
          </div>
        </div>
      </div>
    </div>

  </section>

  <!-- about section -->
  <section class="about_section layout_padding">
    <div class="container">
      <div class="col-md-11 col-lg-10 mx-auto">
        <div class="heading_container heading_center">
          <h2>
            About Us
          </h2>
        </div>
        <div class="box">
          <div class="col-md-7 mx-auto">
            <div class="img-box">
              <img src="{% static 'MenuFacil/images/about-img.jpg' %}" class="box-img" alt="">
            </div>
          </div>
          <div class="detail-box">
            <p>
            MenuFácil stands out as a versatile platform, offering a convenient way to explore menus from a variety of restaurants. Through the use of QR codes, users can effortlessly peruse diverse culinary options and place orders seamlessly. 
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- client section -->
  <section class="client_section layout_padding">
    <div class="container">
      <div class="col-md-11 col-lg-10 mx-auto">
        <div class="heading_container heading_center">
          <h2>
            Testimonial
          </h2>
        </div>
        <div id="customCarousel1" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="detail-box">
                <h4>
                  Rodrigo B. 
                </h4>
                <p>
                    MenuFácil's mobile app has streamlined the way I order food. The QR code feature is genius, allowing me to quickly check out menus from multiple restaurants and place orders in a snap. It's become an essential tool for my culinary adventures!
                </p>
                <i class="fa fa-quote-left" aria-hidden="true"></i>
              </div>
            </div>
            <div class="carousel-item">
              <div class="detail-box">
                <h4>
                  Mauro
                </h4>
                <p>
                    MenuFácil has made exploring new flavors so much fun! The mobile app gives me instant access to a range of restaurant menus, and ordering is as simple as scanning a QR code. It's the perfect companion for anyone who enjoys a diverse and hassle-free dining experience.
                </p>
                <i class="fa fa-quote-left" aria-hidden="true"></i>
              </div>
            </div>
            <div class="carousel-item">
              <div class="detail-box">
                <h4>
                  Mateus
                </h4>
                <p>
                    I love how MenuFácil turns my smartphone into a virtual menu library. It's incredibly convenient to browse through various culinary options and place orders effortlessly. A game-changer for anyone who enjoys exploring different cuisines!
                </p>
                <i class="fa fa-quote-left" aria-hidden="true"></i>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev d-none" href="#customCarousel1" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#customCarousel1" role="button" data-slide="next">
            <i class="fa fa-arrow-right" aria-hidden="true"></i>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

src/restaurant/templates/restaurant/qrcode.html
{% load static %}
{% load qr_code %}

<html>
  <head>
    <meta charset="utf-8" />
  </head>
  <body style="margin:0">
    <main>
      <div>
        {% if tab_id %}
          {% qr_from_text tab_id size="m" image_format="png" error_correction="L" %}
        {% else %}
          <h1>Error Displaying QRCode</h1>
        {% endif %}
      </div>
    </main>
  </body>
</html>

src/restaurant/templates/restaurant/sales.html
{% load static %}

<html>
  <head>
    <meta charset="utf-8" />
  </head>
  <body style="margin:0">
    <main>
      <div>
        {% if restaurant %}
          <h1>{{ restaurant.name }}</h1>
          {% now 'd/m/Y H:i' %}
          {% if restaurant.get_most_popular_foods %}
            <h2>Most Popular Food</h2>
            {% for food in restaurant.get_most_popular_foods %}
              <p>{{ food.name }} - {{ food.get_total_sales }} -  R${{ food.get_total_sales_amount|floatformat:2 }}</p>
            {% endfor %}
            <h2>Total Sales</h2>
            <p>{{ restaurant.get_total_sales }}</p>
            <h2>Total Sales Amount</h2>
            <p>R${{ restaurant.get_total_sales_amount|floatformat:2 }}</p>
          {% else %}
            <h2>No Sales Reported</h2>
          {% endif %}
        {% else %}
          <h1>Error Displaying Sales</h1>
        {% endif %}
      </div>
    </main>
  </body>
</html>