src/account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'account'
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("change/", auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('account:logout')), name="password_change"),
    path("login", auth_views.LoginView.as_view(), name="login"),
    path("", views.index, name="profile"),
    path("<int:pk>/delete", views.UserDelete.as_view(), name="delete"),
    path("logout/", views.logout_view, name="logout"),
    path("change_done/", views.logout_view, name="password_change_done"),
]

src/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path("add/", views.add, name="add"),
    path("inc/", views.increase_quantity, name="inc"),
    path("dec/", views.decrease_quantity, name="dec"),
    path("remove/", views.remove, name="remove"),
    path('', views.details, name="details"),
]

src/menuFacil/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from . import views, settings

admin.site.site_title = "Menu Fácil site admin"
admin.site.site_header = "Menu Fácil administration"
admin.site.index_title = "Menu Fácil administration"

urlpatterns = [
    path("", views.index, name="home"),
    path("account/", include("account.urls")),
    path('admin/', admin.site.urls),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("restaurant/", include("restaurant.urls")),
    path("tab/", include("tab.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT})]
    urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT})]

src/restaurant/urls.py
from django.urls import path

from . import views

app_name = 'restaurant'
urlpatterns = [
    path('', views.RestaurantsView.as_view(), name='index'),
    path('<uuid:restaurant_id>/', views.menu, name='detail'),
    path('qrcode/<uuid:tab_id>/', views.get_qrcode, name='qrcode'),
    path('sales/<uuid:restaurant_id>/', views.sales, name='sales'),
    path('search/', views.search, name='search')
]

src/tab/urls.py
from django.urls import path

from . import views

app_name = 'tab'
urlpatterns = [
    path('', views.details, name='details'),
    path('present/', views.present, name='present'),
    path('history/', views.history, name='history'),
    path('paid/', views.paid, name='paid'),
    path('pay/physical/', views.pay_physical, name='physical'),
    path('pay/online/', views.pay_online, name='online'),
    path('pay/confirm/', views.confirm_payment, name='confirm'),
    path('remove/', views.remove_tab, name='remove'),
    path('get_page/', views.get_tab_page, name='get_page')
]

src/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
{% load static %}
{% load cart_tags %}
<html>
  <head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <title>
      {% block title %}
        Base Page - menuFacil
      {% endblock %}
    </title>

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'menuFacil/css/bootstrap.css' %}" />

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet">

    <!-- font awesome style -->
    <link href="{% static 'menuFacil/css/font-awesome.min.css' %}" rel="stylesheet" />
    <!-- nice select -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha256-mLBIhmBvigTFWPSCtvdu6a76T+3Xyt+K571hupeFLg4=" crossorigin="anonymous" />
    <!-- slidck slider -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css" integrity="sha256-UK1EiopXIL+KVhfbFa8xrmAWPeBjMVdvYMYkTAEv/HI=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css.map" integrity="undefined" crossorigin="anonymous" />

    <!-- Custom styles for this template -->
    <link href="{% static 'menuFacil/css/style.css' %}" rel="stylesheet" />
    <!-- responsive style -->
    <link href="{% static 'menuFacil/css/responsive.css' %}" rel="stylesheet" />

    <!-- jQery -->
    <script src="{% static 'menuFacil/js/jquery-3.7.1.min.js' %}"></script>
    
    {% block head %}
    {% endblock %}
  </head>
  
  <body>
    

      {% block topbar %}
        <div class="hero_area">
          <!-- header section strats -->
          <header class="header_section">
            <div class="container-fluid">
              <nav class="navbar navbar-expand-lg custom_nav-container">
                <a class="navbar-brand" href="{% url 'restaurant:index' %}">
                  <span>
                    MenuFácil
                  </span>
                </a>
                <div class="" id="">
                  {% if user.is_authenticated %}
                    <div class="User_option">
                      <a href="{% url 'account:profile' %}">
                        <i class="fa fa-user-circle" aria-hidden="true"></i>
                        <span>Account: {{ user.username }}</span>
                      </a>
                  {% else %}
                    <div class="User_option">
                      <a href="{% url 'account:login' %}">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <span>Login</span>
                      </a>
                      <a href="{% url 'account:signup' %}">
                        <i class="fa fa-sign-in" aria-hidden="true"></i>
                        <span>Sign Up</span>
                      </a>
                  {%endif%}
                    </div>
                  <div class="custom_menu-btn">
                    <button onclick="openNav()">
                      <img src="{% static 'MenuFacil/images/menu.png'%}">
                    </button>
                  </div>
                  <div id="myNav" class="overlay">
                    <div class="overlay-content">
                      <a href="{% url 'restaurant:index' %}">Home</a>
                      {% if user.is_authenticated %}

                        {% if user.is_staff %}
                          <a href="{% url 'admin:index' %}">Admin</a>
                        {% endif %}

                        <a href="{% url 'tab:history' %}">History</a>

                      {% else %}
                        <a href="{% url 'account:login' %}">Log In</a>
                        <a href="{% url 'account:signup' %}">Sign Up</a>
                      {% endif %}
                      
                      {% cart_length cart.id request.session request.user as cart_length %}
                      <a href="{% url 'cart:details' %}">
                        Cart {% if cart_length %}({{ cart_length }}){% endif %}
                      </a>
                      <a href="{% url 'tab:details' %}">Tab</a>
                    </div>
                  </div>
                </div>
              </nav>
            </div>
          </header>

          <div class="messages">
            {% if messages %}
              {% for message in messages %}
                <a{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</a>
              {% endfor %}
            {% endif %}
          </div> 

          {% block slider %}
          {% endblock %}
        </div>
      {% endblock %}
       
      {% block content %}
      {% endblock %}
   
    <div class="footer_container">
      <!-- info section -->
      <section class="info_section ">
        <div class="container">
          <div class="contact_box">
            <a href="">
              <i class="fa fa-map-marker" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-phone" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-envelope" aria-hidden="true"></i>
            </a>
          </div>
          <div class="info_links">
            <ul>
              <li class="active">
                <a href="{% url 'restaurant:index' %}">MenuFacil Home</a>
              </li>
            </ul>
          </div>
          <div class="social_box">
            <a href="">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-linkedin" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </section>
      <!-- end info_section -->

      <!-- footer section -->
      <footer class="footer_section">
        <div class="container">
          <p>
            &copy; <span id="displayYear"></span> All Rights Reserved By MenuFacil LTDA<br>
          </p>
        </div>
      </footer>
    </div>

    <script src="{% static 'menuFacil/js/bootstrap.js' %}"></script>
    <!-- slick  slider -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.js"></script>
    <!-- nice select -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js" integrity="sha256-Zr3vByTlMGQhvMfgkQ5BtWRSKBGa2QlspKYJnkjZTmo=" crossorigin="anonymous"></script>
    <script src="{% static 'menuFacil/js/custom.js' %}"></script>
    
    <script>
      function SendPost(csrf, url, data, success, error) {
        $.ajax({
          url: url,
          type: "POST",
          headers: {'X-CSRFToken': csrf},
          data: data,
          dataType: "json",
          success: success,
          error: error
        });
      }
    </script>
  </body>
</html>