src/menuFacil/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from . import views, settings

admin.site.site_title = "Menu Fácil site admin"
admin.site.site_header = "Menu Fácil administration"
admin.site.index_title = "Menu Fácil administration"

urlpatterns = [
    path("", views.index, name="home"),
    path("account/", include("account.urls")),
    path('admin/', admin.site.urls),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("restaurant/", include("restaurant.urls")),
    path("tab/", include("tab.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT})]
    urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT})]

src/order/urls.py
from django.urls import path

from . import views

app_name = 'order'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('cancel/', views.cancel, name='cancel'),
]

src/tab/urls.py
from django.urls import path

from . import views

app_name = 'tab'
urlpatterns = [
    path('', views.details, name='details'),
    path('present/', views.present, name='present'),
    path('history/', views.history, name='history'),
    path('paid/', views.paid, name='paid'),
    path('pay/physical/', views.pay_physical, name='physical'),
    path('pay/online/', views.pay_online, name='online'),
    path('pay/confirm/', views.confirm_payment, name='confirm'),
    path('remove/', views.remove_tab, name='remove'),
    path('get_page/', views.get_tab_page, name='get_page')
]

src/item/models.py
from uuid import uuid4
from decimal import Decimal
from django.db import models

from cart.models import Cart
from order.models import Order
from restaurant.models import Food


# Create your models here.
class Item(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    cart = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    food = models.ForeignKey(Food, on_delete=models.PROTECT)
    quantity = models.IntegerField(default=1)
    price: Decimal = models.DecimalField(
                                            max_digits=6,
                                            decimal_places=2,
                                            default=0.00 # type: ignore
                                        )

    def get_price(self) -> Decimal:
        return self.price

    def get_total_price(self) -> Decimal:
        return self.quantity * self.price

src/order/models.py
from uuid import uuid4
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from restaurant.models import Restaurant

class Order(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.SET_NULL, editable=False, null=True)

    tab_type = models.ForeignKey(ContentType, on_delete=models.SET_NULL, editable=False, null=True)
    tab_id = models.UUIDField(editable=False, null=True)
    tab = GenericForeignKey('tab_type', 'tab_id')

    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    pending_cancellation = models.BooleanField(default=False)

    class StatusType(models.TextChoices):
        MADE = ("MD", "Made")
        IN_PROGRESS = ("IP", "In Progress")
        DELIVERED = ("DV", "Delivered")
        CANCELLED = ("CL", "Cancelled")

        def __str__(self):
            return self.label

    status = models.CharField(
        max_length=2,
        choices=StatusType.choices,
        default=StatusType.MADE,
    )

    def get_length(self) -> int:
        return sum(item.quantity for item in self.item_set.all()) # type: ignore

    def get_total_price(self) -> float:
        return sum(item.get_total_price() for item in self.item_set.all()) # type: ignore

    def __str__(self):
        return f'{self.get_total_price()} - {self.created_at.strftime(" %H:%M %d/%m/%Y")}'  # pylint: disable=maybe-no-member # type: ignore

src/tab/models.py
from uuid import uuid4
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation

from restaurant.models import Restaurant
from order.models import Order

class AbstractTab(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    client = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        editable=False,
        null=True,
    )
    restaurant = models.ForeignKey(
        Restaurant,
        on_delete=models.SET_NULL,
        editable=False,
        null=True,
    )
    order = GenericRelation(
        Order,
        content_type_field="tab_type",
        object_id_field="tab_id"
    )

    class Meta:
        abstract = True

    def get_total_price(self) -> float:
        return sum(order.get_total_price() for order in self.order.all())

class Tab(AbstractTab):
    def __str__(self) -> str:
        return str(self.id).split('-')[0]

class HistoricTab(AbstractTab):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    client = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        editable=False,
        null=True,
    )

src/tab/forms.py
from django import forms
from creditcards.forms import CardNumberField, CardExpiryField, SecurityCodeField

class PaymentForm(forms.Form):
    name_on_card = forms.CharField(max_length=50, required=True)
    cc_number = CardNumberField(label='Card Number')
    cc_expiry = CardExpiryField(label='Expiration Date')
    cc_code = SecurityCodeField(label='CVV/CVC')

src/tab/views.py
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from order.models import Order

from tab.models import HistoricTab, Tab
from menuFacil.validation import  contains, valid_uuid
from .forms import PaymentForm

TAB_KEY = 'tab_token'

# Create your views here.
def details(request: HttpRequest) -> HttpResponse:
    if request.user.is_authenticated:
        request.session[TAB_KEY] = str(request.user.tab.id) # type: ignore

    if TAB_KEY not in request.session.keys():
        return redirect("tab:present")

    try:
        tab = Tab.objects.get(id=request.session[TAB_KEY])
    except Tab.DoesNotExist:
        messages.error(request, "Error in getting your Tab")
        request.session.pop(TAB_KEY)
        return redirect("tab:present")

    orders = tab.order.all()
    orders = orders.order_by('-created_at').reverse()
    ctx = {
            'orders': orders,
            'tab': tab,
        }

    return render(request, 'tab/details.html', ctx)

def present(request: HttpRequest) -> HttpResponse:
    if request.method != "POST":
        if TAB_KEY in request.session.keys():
            return redirect("tab:details")
        return render(request, 'tab/present.html')

    if not contains(request.POST, ['tab']) or \
       not valid_uuid(request.POST['tab']) or \
       not Tab.objects.filter(id=request.POST['tab']).exists():
        return JsonResponse({"success": False}, status=400)

    request.session[TAB_KEY] = request.POST['tab']

    return JsonResponse({"success": True}, status=200)

def pay_physical(request: HttpRequest) -> HttpResponse:
    if TAB_KEY not in request.session.keys():
        messages.error(request, "Error in getting your Tab")
        return redirect("tab:details")
    return render(request, 'tab/physical.html', {"tab_id": request.session[TAB_KEY]})

@require_http_methods(["GET", "POST"])
def pay_online(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = PaymentForm(request.POST)
        if form.is_valid():
            if TAB_KEY in request.session.keys():
                if tab_has_been_paid(request.session[TAB_KEY]):
                    return redirect("tab:paid")
        else:
            for error in form.errors:
                print(error)
        messages.error(request, "Error in paying your Tab")
    form = PaymentForm()
    return render(request, 'tab/online.html', {"form": form})

@login_required(login_url="/account/login/")
def history(request: HttpRequest) -> HttpResponse:
    return render(request, 'tab/history.html',
        {
            'historic_tabs': HistoricTab.objects.filter(client=request.user).order_by('-created_at').reverse()
        }
    )

@staff_member_required
def confirm_payment(request: HttpRequest) -> HttpResponse:
    return render(request, 'tab/confirm.html')

@require_http_methods(["GET"])
def remove_tab(request: HttpRequest) -> HttpResponse:
    if TAB_KEY not in request.session.keys():
        messages.error(request, "Error in getting your Tab")
        return redirect("tab:details")

    if Tab.objects.get(id=request.session[TAB_KEY]).order.count() != 0:
        messages.error(request, "Your tab hasn't been paid yet")
        return redirect("tab:details")

    if request.user.is_authenticated:
        messages.error(request, "You can't remove a tab if you are logged in")
        return redirect("tab:details")

    messages.success(request, "Tab Removed Successfully")
    request.session.pop(TAB_KEY)
    return redirect('home')


@require_http_methods(["GET"])
def paid(request: HttpRequest) -> HttpResponse:
    if TAB_KEY not in request.session.keys():
        messages.error(request, "Error in getting your Tab")
        return redirect("tab:details")
    if Tab.objects.get(id=request.session[TAB_KEY]).order.count() == 0:
        messages.success(request, "Tab paid successfully")
        if not request.user.is_authenticated:
            request.session.pop(TAB_KEY)
        return redirect('home')
    messages.error(request, "Tab hasn't been paid yet")
    return redirect("tab:details")


def tab_has_been_paid(tab_id: str) -> bool:
    tab = get_object_or_404(Tab, id=tab_id)

    new_tab: HistoricTab | None
    if tab.client is None:
        new_tab = None
    else:
        new_tab = HistoricTab.objects.create(
            client=tab.client,
            restaurant=tab.restaurant,
        )
        tab.restaurant = None

    order: Order
    for order in tab.order.all():
        order.tab = new_tab
        order.save()

    tab.save()
    return True

@staff_member_required
@require_http_methods(["POST"])
def get_tab_page(request: HttpRequest) -> HttpResponse:
    if not contains(request.POST, ['tab']) or \
       not valid_uuid(request.POST['tab']) or \
       not Tab.objects.filter(id=request.POST['tab']).exists():
        return JsonResponse({"success": False}, status=400)

    url = reverse("admin:tab_tab_change", args=[request.POST['tab']])

    return JsonResponse({"success": True, "redirect": url}, status=200)

src/tab/templates/tab/confirm.html
{% extends "base.html" %}
{% load static %}

{% block title %}Confirm paid Tab{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'restaurant/css/index.css' %}" />
    <script src="{% static 'tab/js/instascan.min.js' %}"></script>
{% endblock %}


{% block content%}
<body class="sub_page">
  

<div>
  <div class="container" style="display: flex; flex-direction: column; width: 1000px">
    <video id="preview" class="camera_scan"></video>
  </div>
  {% csrf_token %}
  <script type="text/javascript">
    var scanner = new Instascan.Scanner({ video: document.getElementById('preview'), scanPeriod: 5, mirror: false });
    
    const URL = "{% url 'tab:get_page' %}";
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

    scanner.addListener('scan', function(content){
      SendPost(csrftoken, URL, {'tab': content},
        function(data, textStatus, jqXHR) {
          window.location.href=data['redirect'];
        },
        function (jqXHR, textStatus, errorThrown) {
            alert('Invalid QRCode!');
        }
      )
    });
    
    Instascan.Camera.getCameras().then(function (cameras){
      let buttons = '<label class="btn btn-primary active"><input type="radio" name="options" value="0" autocomplete="off" checked>' + cameras[0].name + '</label>';
      for(let i = 1; i < cameras.length; i++) {
        buttons += '\n<label class="btn btn-secondary">';
        buttons += '<input type="radio" name="options" value="' + i +'" autocomplete="off">';
        buttons += cameras[i].name + '</label>';
      }
      el = document.getElementById('result');
      el.innerHTML = buttons;

      if(cameras.length>0){
        scanner.start(cameras[0]);
        $('[name="options"]').on('change',function(){
            if(cameras[$(this).val()]!=""){
              scanner.start(cameras[$(this).val()]);
            }else{
              alert('No camera found in button!');
            }
        });
      }else{
        console.error('No cameras found.');
        alert('No cameras found.');
      }
    }).catch(function(e){
      console.error(e);
      alert(e);
    });
  </script>

  <div class="camera-buttons container" data-toggle="buttons" id="result" style="display: flex; flex-direction: column; width: 200px; padding: 10px">
  </div>
</div>
</body>
{% endblock %}

src/tab/templates/tab/details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Your Tab
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static 'tab/css/details.css' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
{% endblock %}

{% block content %}
<body class="sub_page">

  <div class="comanda" style="padding-bottom: 50vh;">
    <h1>Your Tab</h1>
    {% if orders %}
      {% csrf_token %}
      <script>
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
        const cancelURL = "{% url 'order:cancel' %}"
      </script>
      <div class="pay-buttons">
        <div class="button">
          <a href="{% url 'tab:online' %}">Pay Online</a>
        </div>
        <div class="button">
          <a href="{% url 'tab:physical' %}">Pay at the Bar</a>
        </div>
      </div>
      <p></p>
      {% for order in orders %}
        <button class="accordion">
          <p>Order #{{ forloop.counter }}</p>
          <p>Status: {{ order.get_status_display }}</p>
          <p>Price: {{ order.get_total_price|floatformat:2 }}</p>
        </button>
        <div class="accordion-content">
          <div class="container-tab">
            <div class="details">
              <table>
                <tr>
                  <td>Order Date:</td>
                  <td>{{ order.created_at|date:'d/m/Y H:i' }}</td>
                </tr>
                <tr>
                  <td>Last Updated:</td>
                  <td>{{ order.updated_at|date:'d/m/Y H:i' }}</td>
                </tr>
              </table>
            </div>

            <table class="table">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Quantity</th>
                  <th>Price</th>
                  <th>Total Price</th>
                </tr>
              </thead>
              <tbody>
                {% for item in order.item_set.all %}
                  <tr>
                    <td>{{ item.food }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.get_price|floatformat:2 }}</td>
                    <td>{{ item.get_total_price|floatformat:2 }}</td>
                  </tr>
                {% endfor %}
              </tbody>
              <tfoot>
                <tr>
                  <td colspan="2"></td>
                  <td>Total:</td>
                  <td>{{ order.get_total_price|floatformat:2 }}</td>
                </tr>
              </tfoot>
            </table>

            <div class="buttons">
              {% if order.status == 'MD' or order.status == 'IP' %}
                {% if not order.pending_cancellation %}
                  <div class="button-danger">
                    <a id="cancel{{ forloop.counter }}">Cancel Order</a>
                    <script>
                      document.getElementById('cancel{{ forloop.counter }}').onclick = function () {
                        SendPost(
                          csrftoken,
                          cancelURL,
                          { order: '{{ order.id }}' },
                          function (data, textStatus, jqXHR) {
                            location.reload()
                          },
                          function (jqXHR, textStatus, errorThrown) {
                            console.log(errorThrown)
                          }
                        )
                      }
                    </script>
                  </div>
                {% else %}
                  <h4>Cancelation Requested</h4>
                {% endif %}
              {% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <p>Your Tab is empty.</p>
      {% if not user.is_authenticated %}
        <a href="{% url 'tab:remove' %}">Remove Tab</a>
      {% endif %}
    {% endif %}
  </div>

  <script>
    var accordions = document.getElementsByClassName('accordion')
    
    for (var i = 0; i < accordions.length; i++) {
      accordions[i].onclick = function () {
        this.classList.toggle('is-open')
    
        var content = this.nextElementSibling
        if (content.style.maxHeight) {
          // accordion is currently open, so close it
          content.style.maxHeight = null
        } else {
          // accordion is currently closed, so open it
          content.style.maxHeight = content.scrollHeight + 'px'
        }
      }
    }
  </script>
</body>
{% endblock %}

src/tab/templates/tab/history.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  History
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static 'tab/css/details.css' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
{% endblock %}

{% block content %}
<body class="sub_page">

  <div class="comanda" style="padding-bottom: 20vh">
    <div class="heading_container heading_center" style="padding-top: 2vh; padding-bottom: 5vh">
      <h1>Your History</h1>
    </div>
    
    {% if historic_tabs %}
        {% for tab in historic_tabs %}
        <button class="accordion">
        <p>Tab #{{ forloop.counter }}</p>
        <p>Restaurant: {{ tab.restaurant.name }}</p>
        <p>Price: {{ tab.get_total_price|floatformat:2 }}</p>
        </button>
        <div class="accordion-content">
        <div class="container">
            {% with orders=tab.order.all %}
                {% if orders %}
                    {% for order in orders %}
                        <button class="accordion">
                        <p>Order #{{ forloop.counter }}</p>
                        <p>Status: {{ order.get_status_display }}</p>
                        <p>Price: {{ order.get_total_price|floatformat:2 }}</p>
                        </button>
                        <div class="accordion-content">
                        <div class="container">
                            <div class="details">
                            <table>
                                <tr>
                                <td>Order Date:</td>
                                <td>{{ order.created_at|date:'d/m/Y H:i' }}</td>
                                </tr>
                                <tr>
                                <td>Last Updated:</td>
                                <td>{{ order.updated_at|date:'d/m/Y H:i' }}</td>
                                </tr>
                            </table>
                            </div>

                            <table class="table">
                            <thead>
                                <tr>
                                <th>Product</th>
                                <th>Quantity</th>
                                <th>Price</th>
                                <th>Total Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in order.item_set.all %}
                                <tr>
                                    <td>{{ item.food }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>{{ item.get_price|floatformat:2 }}</td>
                                    <td>{{ item.get_total_price|floatformat:2 }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                <td colspan="2"></td>
                                <td>Total:</td>
                                <td>{{ order.get_total_price|floatformat:2 }}</td>
                                </tr>
                            </tfoot>
                            </table>

                            <div class="buttons">
                            {% if order.status == 'MD' or order.status == 'IP' %}
                                {% if order.pending_cancellation %}
                                <h4>Cancelation Requested</h4>
                                {% endif %}
                            {% endif %}
                            </div>
                        </div>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
        </div>
        {% endfor %}
    {% else %}
        <h3>You have no history</h3>
    {% endif %}
  </div>

  <script>
    var accordions = document.getElementsByClassName('accordion')
    
    for (var i = 0; i < accordions.length; i++) {
      accordions[i].onclick = function () {
        this.classList.toggle('is-open')
    
        var content = this.nextElementSibling
        if (content.style.maxHeight) {
          // accordion is currently open, so close it
          content.style.maxHeight = null
        } else {
          // accordion is currently closed, so open it
          content.style.maxHeight = content.scrollHeight + 'px'
        }
      }
    }
  </script>
</body>
{% endblock %}

src/tab/templates/tab/online.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Pay Online
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static 'tab/css/details.css' %}" />
{% endblock %}

{% block content %}
<body class="sub_page">
{% load crispy_forms_tags %}
<div class="container" style="padding: 10vh">
  <div class="form">
    <form method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Pay</button>
    </form>
  </div>
</div>
</body>
{% endblock %}

src/tab/templates/tab/pay.html
{% extends "base.html" %}
{% load static %}

{% block title %}Confirm Payed Tab{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'restaurant/css/index.css' %}" />
    <script src="{% static 'tab/js/instascan.min.js' %}"></script>
{% endblock %}


{% block content%}
<body class="sub_page">
  

<div>
  <div class="container" style="display: flex; flex-direction: column; width: 1000px">
    <video id="preview" class="camera_scan"></video>
  </div>
  {% csrf_token %}
  <script type="text/javascript">
    var scanner = new Instascan.Scanner({ video: document.getElementById('preview'), scanPeriod: 5, mirror: false });
    
    const URL = "{% url 'tab:payed' %}";
    const redirectURL = "{% url 'home' %}";
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

    scanner.addListener('scan', function(content){
      SendPost(csrftoken, URL, {'tab': content},
        function(data, textStatus, jqXHR) {
            alert('Tab has been payed!');
            window.location.href=redirectURL;
        },
        function (jqXHR, textStatus, errorThrown) {
            alert('Invalid QRCode!');
        }
      )
    });
    
    Instascan.Camera.getCameras().then(function (cameras){
      let buttons = '<label class="btn btn-primary active"><input type="radio" name="options" value="0" autocomplete="off" checked>' + cameras[0].name + '</label>';
      for(let i = 1; i < cameras.length; i++) {
        buttons += '\n<label class="btn btn-secondary">';
        buttons += '<input type="radio" name="options" value="' + i +'" autocomplete="off">';
        buttons += cameras[i].name + '</label>';
      }
      el = document.getElementById('result');
      el.innerHTML = buttons;

      if(cameras.length>0){
        scanner.start(cameras[0]);
        $('[name="options"]').on('change',function(){
            if(cameras[$(this).val()]!=""){
              scanner.start(cameras[$(this).val()]);
            }else{
              alert('No camera found in button!');
            }
        });
      }else{
        console.error('No cameras found.');
        alert('No cameras found.');
      }
    }).catch(function(e){
      console.error(e);
      alert(e);
    });
  </script>

  <div class="camera-buttons container" data-toggle="buttons" id="result" style="display: flex; flex-direction: column; width: 200px; padding: 10px">
  </div>
</div>
</body>
{% endblock %}

src/tab/templates/tab/physical.html
{% extends 'base.html' %}
{% load static %}
{% load qr_code %}

{% block title %}
  Pay Physically
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static 'tab/css/details.css' %}" />
{% endblock %}

{% block content %}
<body class="sub_page">
  
  <div class="comanda" style="padding: 10vh">
    {% if tab_id %}
      <h1>Show This QRCode to the Cashier</h1>
      {% qr_from_text tab_id size="M" %}
      <div class="button">
        <a href="{% url 'tab:paid' %}">Done</a>
      </div>
    {% else %}
      <h1>There is no tab to pay</h1>
    {% endif %}
  </div>
</body>
{% endblock %}

src/tab/templates/tab/present.html
{% extends "base.html" %}
{% load static %}

{% block title %}Present Tab QRCode{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'restaurant/css/index.css' %}" />
    <script src="{% static 'tab/js/instascan.min.js' %}"></script>
{% endblock %}


{% block content%}
<body class="sub_page">

<div >
  <div class="container" style="display: flex; flex-direction: column; width: 1000px">
    <video id="preview" class="camera_scan"></video>
  </div>
  {% csrf_token %}
  <script type="text/javascript">
    var scanner = new Instascan.Scanner({ video: document.getElementById('preview'), scanPeriod: 5, mirror: false });
    
    const URL = "{% url 'tab:present' %}";
    const redirectURL = "{% url 'home' %}";
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

    scanner.addListener('scan', function(content){
      SendPost(csrftoken, URL, {'tab': content},
        function(data, textStatus, jqXHR) {
            alert('Successfully presented tab!');
            window.location.href=redirectURL;
        },
        function (jqXHR, textStatus, errorThrown) {
            alert('Invalid QRCode!');
        }
      )
    });
    
    Instascan.Camera.getCameras().then(function (cameras){
      let buttons = '<label class="btn btn-primary active"><input type="radio" name="options" value="0" autocomplete="off" checked>' + cameras[0].name + '</label>';
      for(let i = 1; i < cameras.length; i++) {
        buttons += '\n<label class="btn btn-secondary">';
        buttons += '<input type="radio" name="options" value="' + i +'" autocomplete="off">';
        buttons += cameras[i].name + '</label>';
      }
      el = document.getElementById('result');
      el.innerHTML = buttons;

      if(cameras.length>0){
        scanner.start(cameras[0]);
        $('[name="options"]').on('change',function(){
            if(cameras[$(this).val()]!=""){
              scanner.start(cameras[$(this).val()]);
            }else{
              alert('No camera found in button!');
            }
        });
      }else{
        console.error('No cameras found.');
        alert('No cameras found.');
      }
    }).catch(function(e){
      console.error(e);
      alert(e);
    });
  </script>

  <div class="camera-buttons container" data-toggle="buttons" id="result" style="display: flex; flex-direction: column; width: 200px; padding: 10px">
  </div>
</div>
</body>
{% endblock %}

src/tab/templates/tab/tab_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Your Tab{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'cart/css/style.css' %}" />
{% endblock %}

{% block content %}

<div class = "comanda">
    <h1>Your Tab</h1>
    {% if orders %}
        {% for order in orders %}
            <div class="comanda-container">
                <div class="comanda-subcontainer">
                    <a href="{% url 'order:list_order' order.id %}">Pedido {{forloop.counter}}</a>
                    <a href="{% url 'order:cancel_order' order.id %}">Cancel Order</a>
                </div>
            </div>
        {% endfor %}
        <a href="">Pay Tab</a>
    {% else %}
        <p>Your shopping cart is empty.</p>
    {% endif %}
</div>
{% endblock %}