src/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path("add/", views.add, name="add"),
    path("inc/", views.increase_quantity, name="inc"),
    path("dec/", views.decrease_quantity, name="dec"),
    path("remove/", views.remove, name="remove"),
    path('', views.details, name="details"),
]

src/menuFacil/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from . import views, settings

admin.site.site_title = "Menu Fácil site admin"
admin.site.site_header = "Menu Fácil administration"
admin.site.index_title = "Menu Fácil administration"

urlpatterns = [
    path("", views.index, name="home"),
    path("account/", include("account.urls")),
    path('admin/', admin.site.urls),
    path("cart/", include("cart.urls")),
    path("order/", include("order.urls")),
    path("restaurant/", include("restaurant.urls")),
    path("tab/", include("tab.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT})]
    urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT})]

src/order/urls.py
from django.urls import path

from . import views

app_name = 'order'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('cancel/', views.cancel, name='cancel'),
]

src/tab/urls.py
from django.urls import path

from . import views

app_name = 'tab'
urlpatterns = [
    path('', views.details, name='details'),
    path('present/', views.present, name='present'),
    path('history/', views.history, name='history'),
    path('paid/', views.paid, name='paid'),
    path('pay/physical/', views.pay_physical, name='physical'),
    path('pay/online/', views.pay_online, name='online'),
    path('pay/confirm/', views.confirm_payment, name='confirm'),
    path('remove/', views.remove_tab, name='remove'),
    path('get_page/', views.get_tab_page, name='get_page')
]

src/cart/models.py
from uuid import uuid4
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, AnonymousUser
from django.contrib.sessions.backends.base import SessionBase
from django.conf import settings
from restaurant.models import Restaurant

CART_KEY = 'cart_token'

# Create your models here.
class Cart(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    client = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True, null=True
    )
    restaurant = models.ForeignKey(
            Restaurant,
            on_delete=models.SET_NULL,
            null=True
        )

    def get_length(self) -> int:
        return sum(item.quantity for item in self.item_set.all()) # type: ignore

    def get_total_price(self) -> float:
        return sum(item.get_total_price() for item in self.item_set.all()) # type: ignore


def get_cart_length(session: SessionBase, user: AbstractBaseUser | AnonymousUser) -> int:
    if user.is_authenticated:
        session[CART_KEY] = str(user.cart.id) # type: ignore

    (cart, created)= Cart.objects.get_or_create(id=session.get(CART_KEY, None),
                        defaults={'client': user if user.is_authenticated else None}
                    )
    if created:
        session[CART_KEY] = str(cart.id)
    return cart.get_length()

src/item/models.py
from uuid import uuid4
from decimal import Decimal
from django.db import models

from cart.models import Cart
from order.models import Order
from restaurant.models import Food


# Create your models here.
class Item(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    cart = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    food = models.ForeignKey(Food, on_delete=models.PROTECT)
    quantity = models.IntegerField(default=1)
    price: Decimal = models.DecimalField(
                                            max_digits=6,
                                            decimal_places=2,
                                            default=0.00 # type: ignore
                                        )

    def get_price(self) -> Decimal:
        return self.price

    def get_total_price(self) -> Decimal:
        return self.quantity * self.price

src/cart/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.contrib import messages
from django.views.decorators.http import require_POST
from restaurant.models import Food, Restaurant

from menuFacil.validation import contains

from tab.views import TAB_KEY
from item.models import Item
from .models import Cart, CART_KEY

# Create your views here.
@require_POST
def add(request: HttpRequest) -> HttpResponse:
    if not contains(request.POST, ['food', 'restaurant']):
        return JsonResponse({"success": False}, status=400)

    if request.user.is_authenticated:
        request.session[CART_KEY] = str(request.user.cart.id) # type: ignore

    (cart, created)= Cart.objects.get_or_create(id=request.session.get(CART_KEY, None),
                        defaults={'client': request.user if request.user.is_authenticated else None}
                    )
    if created:
        request.session[CART_KEY] = str(cart.id)

    if cart.restaurant is None:
        cart.restaurant = Restaurant.objects.get(id=request.POST['restaurant'])
    elif str(cart.restaurant.id) != request.POST['restaurant']:
        messages.error(request, 'Cannot add items from multiple restaurant to cart')
        return JsonResponse({"success": False}, status=406)

    cart.save()

    # We use filter and first because if it doesn't find it returns None
    item: Item = cart.item_set.filter(food_id=request.POST['food']).first() # type: ignore

    if item is None:
        food = get_object_or_404(Food, id=request.POST['food'])
        item = cart.item_set.create( # type: ignore
            food=food,
            order=None,
            price=food.get_price(),
        )
    else:
        item.quantity += 1
        item.save()

    messages.success(request, 'Item added to cart')
    return JsonResponse({"success": True}, status=200)

@require_POST
def increase_quantity(request: HttpRequest) -> HttpResponse:
    if not contains(request.POST, ['item']):
        return JsonResponse({"success": False}, status=400)

    item = get_object_or_404(Item, id=request.POST['item'])
    item.quantity += 1
    item.save()
    messages.success(request, 'Item quantity increased')
    return JsonResponse({"success": True}, status=200)

@require_POST
def decrease_quantity(request: HttpRequest) -> HttpResponse:
    if not contains(request.POST, ['item']):
        return JsonResponse({"success": False}, status=400)

    item = get_object_or_404(Item, id=request.POST['item'])
    if item.quantity > 1:
        item.quantity -= 1
        item.save()
        messages.success(request, 'Item quantity decreased')
    else:
        item.delete()
        cart = item.cart
        if cart is not None and cart.item_set.count() == 0: # type: ignore
            cart.restaurant = None
            cart.save()
        messages.success(request, 'Item removed from cart')
    return JsonResponse({"success": True}, status=200)

@require_POST
def remove(request: HttpRequest) -> HttpResponse:
    if not contains(request.POST, ['item']):
        return JsonResponse({"success": False}, status=400)

    item = get_object_or_404(Item, id=request.POST['item'])
    cart = item.cart

    item.delete()
    if cart is not None and cart.item_set.count() == 0: # type: ignore
        cart.restaurant = None
        cart.save()

    messages.success(request, 'Item removed from cart')
    return JsonResponse({"success": True}, status=200)

def details(request: HttpRequest) -> HttpResponse:
    if request.user.is_authenticated:
        request.session[CART_KEY] = str(request.user.cart.id) # type: ignore
        request.session[TAB_KEY] = str(request.user.tab.id) # type: ignore

    (cart, created)= Cart.objects.get_or_create(id=request.session.get(CART_KEY, None),
                        defaults={'client': request.user if request.user.is_authenticated else None}
                    )
    if created:
        request.session[CART_KEY] = str(cart.id)

    return render(request, 'cart/details.html', {'cart': cart})

src/cart/templates/cart/details.html
{% extends 'base.html' %}
{% load static %}
{% load tab_tags %}

{% block title %}
  Your Cart
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static 'cart/css/style.css' %}" />
  {% csrf_token %}
  <script>
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
  </script>
{% endblock %}

{% block content %}
<body class="sub_page">

  <div class="carrinho" style="padding-bottom: 400px;">
    {% if cart.item_set.count > 0 %}
      <table class="table">
        <thead>
          <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total Price</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart.item_set.all %}
            <tr>
              <td>{{ item.food }}</td>
              <td>
                <a id="inc{{ forloop.counter }}">+</a>
                {{ item.quantity }}
                <a id="dec{{ forloop.counter }}">-</a>
              </td>
              <td>{{ item.get_price|floatformat:2 }}</td>
              <td>{{ item.get_total_price|floatformat:2 }}</td>
              <td>
                <a id="remove{{ forloop.counter }}">Remove</a>
              </td>
              <script>
                const item_links = {"inc": "{% url 'cart:inc' %}", "dec": "{% url 'cart:dec' %}", "remove": "{% url 'cart:remove' %}"}
                for(const [key, value] of Object.entries(item_links)) {
                  document.getElementById(key + "{{ forloop.counter }}").onclick = function () {
                    SendPost(
                      csrftoken,
                      value,
                      { item: "{{ item.id }}" },
                      function (data, textStatus, jqXHR) {
                        location.reload()
                      },
                      function (jqXHR, textStatus, errorThrown) {
                        console.log(errorThrown)
                        location.reload()
                      }
                    )
                  }
                }
              </script>
            </tr>
          {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <td>
              <a class="btn btn-primary" id="checkout">Checkout</a>
            </td>
            <td colspan="2"></td>
            <td>Total:</td>
            <td>{{ cart.get_total_price|floatformat:2 }}</td>
          </tr>
        </tfoot>
      </table>

      <script>
        const URL = "{% url 'order:create' %}"
        const successURL = "{% url 'tab:details' %}"
        const errorURL = "{% url 'tab:present' %}"
        
        document.getElementById('checkout').onclick = function () {
          SendPost(
            csrftoken,
            URL,
            { cart: '{{ cart.id }}',
              tab: '{{ request.session|get_item:"tab_token" }}' 
            },
            function (response) {
              window.location.href = successURL
            },
            function (error) {
              if (error.status == 412) {
                window.location.href = errorURL
              } else {
                console.log(error)
                location.reload()
              }
            }
          )
        }
      </script>
    {% else %}
      <p>Your shopping cart is empty.</p>
    {% endif %}
  </div>
</body>
{% endblock %}